steps:
    # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/sam-sandbox-24911/github.com/samweeks92/react-demo-stateless-frontend:$SHORT_SHA", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/sam-sandbox-24911/github.com/samweeks92/react-demo-stateless-frontend:$SHORT_SHA"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=kubernetes/deployment-service.yaml
    - --image=gcr.io/sam-sandbox-24911/github.com/samweeks92/react-demo-stateless-frontend:$SHORT_SHA
    - --location=europe-west2
    - --cluster=cluster-1