apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-demo
  template:
    metadata:
      labels:
        app: react-demo
    spec:
      containers:
      - name: react-frontend
        image: gcr.io/sam-sandbox-243911/github.com/samweeks92/react-demo-stateless-frontend:1.0
        ports:
        - name: container-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-demo-service
spec:
  selector:
    app: react-demo
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80